license="${mod_license}"
issueTrackerURL="https://github.com/Sjouwer/gamma-utils/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/Sjouwer/gamma-utils"
logoFile="assets/gammautils/icon.png"
authors="Sjouwer"
description="Gamma / Brightness / Night Vision mod, making it easy to see in the dark."

[[mixins]]
config="${mod_id}.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[modproperties.${mod_id}]
"sodium:config_api_user" = "io.github.sjouwer.gammautils.compat.SodiumConfigBuilder"

["badoptimizations:cache_hooks"]
lightmap = "io.github.sjouwer.gammautils.compat.BadOptimizationsHook"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="cloth_config"
    type="required"
    versionRange="[${cloth_config_version},)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"