# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          21,    # Is a Current Java LTS, make sure is a minimum supported by Minecraft
        ]
        # and run on both Linux and Windows
        os: [windows-2022]
        # to run on Linux: os: [ubuntu-22.04] (if want artifacts from Linux, other changes needed)
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'oracle'
          # by default Github uses Microsoft one to restore change to 'microsoft'
#      - name: make gradle wrapper executable
#        if: ${{ runner.os != 'Windows' }}
#        run: chmod +x ./gradlew
# not needed on Windows
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        if: ${{ runner.os == 'Windows' && matrix.java == '21' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
